// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMhwGOTDfqI-LkN7Hhc5OMxEKW6hMj--I',
    appId: '1:73927423632:web:00ea0176b0aa4edc834a15',
    messagingSenderId: '73927423632',
    projectId: 'my-first-project-d6b7a',
    authDomain: 'my-first-project-d6b7a.firebaseapp.com',
    storageBucket: 'my-first-project-d6b7a.appspot.com',
    measurementId: 'G-17DGHRKEND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBF77dvio02mAOFDOQ1VEwLc2UKnera7s',
    appId: '1:73927423632:android:cb1c05fb0ad6c3f0834a15',
    messagingSenderId: '73927423632',
    projectId: 'my-first-project-d6b7a',
    storageBucket: 'my-first-project-d6b7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6EOV6-ybSTti5VqXcaZhNRJ-TYrrTfLo',
    appId: '1:73927423632:ios:c648de5fc61ab007834a15',
    messagingSenderId: '73927423632',
    projectId: 'my-first-project-d6b7a',
    storageBucket: 'my-first-project-d6b7a.appspot.com',
    iosClientId:
        '73927423632-s9e0s5cl8p5cirn223lu68pvvpc5q8q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCoffeeBrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6EOV6-ybSTti5VqXcaZhNRJ-TYrrTfLo',
    appId: '1:73927423632:ios:c648de5fc61ab007834a15',
    messagingSenderId: '73927423632',
    projectId: 'my-first-project-d6b7a',
    storageBucket: 'my-first-project-d6b7a.appspot.com',
    iosClientId:
        '73927423632-s9e0s5cl8p5cirn223lu68pvvpc5q8q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCoffeeBrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6EOV6-ybSTti5VqXcaZhNRJ-TYrrTfLo',
    appId: '1:73927423632:ios:c648de5fc61ab007834a15',
    messagingSenderId: '73927423632',
    projectId: 'my-first-project-d6b7a',
  );
}
